version: 2
updates:
  - package-ecosystem: "npm"
    versioning-strategy: "increase"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "automerge"
      - "auto-approve"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "@types/node"
      # For providers, ignore all patch updates for version updates only
      - dependency-name: "@cdktf/provider-*"
        update-types: ["version-update:semver-patch"]
    groups:
      cdktf:
        patterns:
          - "cdktf"
          - "cdktf-cli"
          - "@cdktf/*"
      jest:
        patterns:
          - "jest"
          - "ts-jest"
          - "@types/jest"
          - "@jest/*"
      aws:
        patterns:
          - "aws-sdk"
          - "@types/aws-lambda"
      lodash:
        patterns:
          - "lodash"
          - "@types/lodash"
      uuid:
        patterns:
          - "uuid"
          - "@types/uuid"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "automerge"
      - "auto-approve"
    # only update hashicorp actions, external actions managed by tsccr
    allow:
      - dependency-name: "hashicorp/*"
